SET hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DbTxnManager;
SET hive.support.concurrency=true;
drop database if exists basic_test cascade;
create database if not exists basic_test;
create table basic_test.test (key int, value string) stored as parquet;
create table basic_test.acid (key int, value string) stored as orc tblproperties('transactional'='true');
create table basic_test.insert_only (key int, value string) stored as orc tblproperties('transactional'='true', 'insert_only'='true');
create table basic_test.acid_bucketed (key int, value string) stored as orc tblproperties('transactional'='true', 'bucketing.enabled'='true', 'bucketing.columns'='key', 'bucketing.num.buckets'='2');
create table basic_test.insert_only_bucketed (key int, value string) stored as orc tblproperties('transactional'='true', 'insert_only'='true', 'bucketing.enabled'='true', 'bucketing.columns'='key', 'bucketing.num.buckets'='2');
insert into basic_test.test values (1, 'a'), (2, 'b'), (3, 'c');
insert into basic_test.acid values (1, 'a'), (2, 'b'), (3, 'c');
insert into basic_test.insert_only values (1, 'a'), (2, 'b'), (3, 'c');
insert into basic_test.acid_bucketed values (1, 'a'), (2, 'b'), (3, 'c');
insert into basic_test.insert_only_bucketed values (1, 'a'), (2, 'b'), (3, 'c');
desc formatted basic_test.test;
desc formatted basic_test.acid;
desc formatted basic_test.insert_only;
desc formatted basic_test.acid_bucketed;
desc formatted basic_test.insert_only_bucketed;
select * from basic_test.test;
select * from basic_test.acid;
select * from basic_test.insert_only;
select * from basic_test.acid_bucketed;
select * from basic_test.insert_only_bucketed;