# demo
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: openmldb_components
    metrics_path: /brpc_metrics
    static_configs:
      - targets: # consists of openmldb components deploy-node/hosts
        - openmldb-compose-ts-1:10921
        - openmldb-compose-ts-2:10921
        - openmldb-compose-ns-1:7527
        - openmldb-compose-api-1:9080
