name: Docker Image For Kafka
on:
  push:
    paths:
      - kafka/Dockerfile
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - uses: actions/checkout@v2

    - name: Build kafka docker
      # Before the cache, it was "run: docker compose build".
      run: |
        docker build kafka --tag ghcr.io/vagetablechicken/kafka-connect:latest
        docker push ghcr.io/vagetablechicken/kafka-connect:latest
